services:
  #Server web&php-Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: erp-predictive-app
    container_name: erp-app
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - erp-network
    depends_on:
      - db

  #La base de donnees
  db:
    image: mysql:8.0
    container_name: erp-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - erp-network

networks:
  erp-network:
    driver: bridge

volumes:
  dbdata:
